exclude: "micropython/src"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
  - repo: local
    hooks:
      - id: stubs
        name: Generate stubs for C files
        entry: ./tools/generate_stubs.py
        language: python
        files: micropython/modules/(.*)/(.*).c
